### ISSUE TITLE
Unknown exception in command

### ISSUE THREAD

**Issue by BazZziliuS** [uskyblock/uSkyBlock#61]
_Please paste the output from `/usb version` below_
```
[09:56:49 INFO]: Name: uSkyBlock
[09:56:49 INFO]: Version: 3.1.0-SNAPSHOT
[09:56:49 INFO]: Description: Ultimate SkyBlock v3.1.0-SNAPSHOT-518f3fa
[09:56:49 INFO]: Language: ru (ru)
[09:56:49 INFO]:   State: d=128, r=64, i=4, p=5, n=true, awe=false
[09:56:49 INFO]: Server: Mohist 1.20.1-863 (MC: 1.20.1)
[09:56:49 INFO]:   State: online=true, bungee=false
[09:56:49 INFO]: ------------------------------
[09:56:49 INFO]: Vault 1.7.3-b131 (ENABLED)
[09:56:49 INFO]: WorldEdit 7.2.17+6544-56d0383 (ENABLED)
[09:56:49 INFO]: WorldGuard 7.0.10-SNAPSHOT+cef4c44 (ENABLED)
[09:56:49 INFO]: ------------------------------
```

_What steps will reproduce the problem?_
1. /is

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* console-error: https://paste.fuix.net/IR3s5cF

(Not following the template will result in closing the issue.)

**Comment by BazZziliuS** [comment]
Too bad. Am I right in understanding that versions below 1.20.3 will no longer be supported?

**Comment by minoneer** [comment]
Is there a particular reason to stay on 1.20.3 instead of 1.20.5? Supporting more, especially older versions of the game, always has an overhead, so I'm trying to understand the benefits.
Ultimately it's @Muspah's call to make :)

**Comment by Muspah** [comment]
I'm all in favor of moving forwards and dropping legacy support when possible, but if there's a good reason to support an older version, I don't mind. But please drop support when possible.

**Comment by BazZziliuS** [comment]
> I'm all in favor of moving forwards and dropping legacy support when possible, but if there's a good reason to support an older version, I don't mind. But please drop support when possible.

This version still includes many popular mods that are regularly updated, which is its main appeal.
I want to launch a server on this version, but this error prevents players from enjoying a seamless gaming experience, and it’s a significant concern for me.
If you could help me find a previous build where this error didn’t occur, I believe it would resolve my issue—especially if the latest version doesn’t include any critical fixes.

**Comment by minoneer** [comment]
I see; I didn't think about moded servers. 

Imho, it doesn't make sense for us to support versions before 1.20.5 going forward. Minecraft completely changed its item system in 1.20.5; therefore we would have to duplicate significant parts of the item specification logic - which is central to the plugin.

However, looking at the build history, we currently have no version compatible with 1.20, 1.20.1, and 1.20.2, since we directly updated to 1.20.3. I therefore forked the pre-1.20.5 version and adjusted it to compile with 1.20.1: https://github.com/uskyblock/uSkyBlock/tree/1.20.1. 

The build is attached below. It is untested, so please proceed with caution and do your own testing. We won't officially support it, but it should be the same version as the one you are currently using (v3.1.0-SNAPSHOT-518f3fa).

Let me know if that works for you.

[uSkyBlock-3.1.0-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/18234171/uSkyBlock-3.1.0-SNAPSHOT.jar.zip)

**Comment by BazZziliuS** [comment]
Thank you very much, everything works.
